//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalProjectEntities : DbContext
    {
        public FinalProjectEntities()
            : base("name=FinalProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<computer> computers { get; set; }
        public virtual DbSet<device> devices { get; set; }
        public virtual DbSet<firewall> firewalls { get; set; }
        public virtual DbSet<router> routers { get; set; }
        public virtual DbSet<server> servers { get; set; }
        public virtual DbSet<@switch> switches { get; set; }
        public virtual DbSet<wap> waps { get; set; }
    }
}
