//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class router
    {

        public int id { get; set; }
        public byte[] intIP { get; set; }
        public byte[] extIP { get; set; }
        public byte[] dns { get; set; }
        public byte[] network { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> installedOn { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
