//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class server
    {
        public string id { get; set; }
        public string os { get; set; }
        public string ip1 { get; set; }
        public string ip2 { get; set; }
        public string ip3 { get; set; }
        public string ip4 { get; set; }
        public string dns { get; set; }
        public string network { get; set; }
        public string roles { get; set; }
        public string location { get; set; }
        public string installedOn { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
