//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @switch
    {
        public int id { get; set; }
        public Nullable<int> type { get; set; }
        public byte[] ip { get; set; }
        public Nullable<System.DateTime> installedOn { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
